language: python

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.7
      env: TOXENV=py37
    - python: 3.7
      env: TOXENV=cov
      after_script:
        - pip install coveralls;
        - coveralls;

branches:
    only:
        - master
        - develop

install: pip install tox

script: tox

